# title: "THE CAT | TRADUCCIONES"
author: "The Cat"
# description: "ES<>EN | Traducci칩n Audiovisual y Literaria | Edici칩n, Subtitulado y Correcci칩n"
permalink: /:title/
lang: "es"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true       # show a sidebar instead of the usual header

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:thecat.translations@gmail.com"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/thecat_translations/"}
  - {title: Linkedin, icon: linkedin, url: "http://www.linkedin.com/company/the-cat-translations/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

# remote_theme: niklasbuschmann/contrast@v2.11

# Idiomas
baseurl: "" # https://github.com/kurtsson/jekyll-multiple-languages-plugin/issues/96
languages: ["es","en"]
exclude_from_localizations: ["javascript", "images", "css"]
defaultLang: es
languageNames:
  es: Espa침ol
  en: English


plugins:
 - jekyll-feed
 - jekyll-multiple-languages-plugin
#  - jekyll-remote-theme